### ISSUE TITLE
How to use selected-deck-changed event

### ISSUE THREAD

**Issue by benjaminliugang** [PredixDev/px-deck-selector#5]
When I use px-deck-selector with px-deck-selector event registered, the event does not fired.
I checked the source file(https://github.com/PredixDev/px-deck-selector/blob/master/px-deck-selector.html), I did find we had fired the event.

**Comment by runn-vermel** [comment]
Hi @benjaminliugang  - i'm going to close this issue. Please use our provided template for submitting  issues. also, if/when you reopen this issue please provide some sample code.
